### ISSUE TITLE
Add typescript definitions 

### ISSUE THREAD

**Issue by ChuckJonas** [forcedotcom/aura#159] opened 2018-04-11 08:37 UTC
It would be really great to get this project on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) so people can use it with typescript.

**Comment by mgetzbw** [comment] 2018-04-11 13:12
Potential duplicate of #49

**Comment by ChuckJonas** [comment] 2018-04-11 19:53
@mgetzbw sort of... #49 almost seem to imply some architecture change.  This would just be adding a [type definition file](http://definitelytyped.org/guides/contributing.html).  There would be no functional changes to achieve this

**Comment by JoernBerkefeld** [comment] 2018-05-17 20:45
+1

**Comment by mgetzbw** [comment] 2018-06-25 16:33
Actually this is more important just for the use of the official VSCode supported editor

**Comment by d0th3do** [comment] 2018-07-30 21:56
Absolutely want.  Is there a community effort for this kind of feature?  I am in the process of converting our Visualforce javascript into a typescript library and moving to Lightning would be much easier with typing definitions for Aura.

**Comment by ChuckJonas** [comment] 2018-07-30 21:59
@d0th3do I'd be willing to help out... I don't use the library, but I'm an advocate for people using typescript with salesforce.  Seem like more or less we'd just need to go through the docs and start breaking it out.

**Comment by d0th3do** [comment] 2018-07-30 22:06
@ChuckJonas yeah, it shouldn't be too difficult to do, but if some of the folks over at forcedotcom were to start up an open source typing library it would be a lot easier to maintain than starting it up on our own.  Despite that I might do it for fun when Lightning starts becoming a necessity or I get bored.

**Comment by ChuckJonas** [comment] 2018-07-30 22:26
@d0th3do typically with this type of stuff, if it's not written in typescript, the types almost always live in  DefinitelyTyped (allows you to do `npm install -D @types/aura`... So even if we started the DefinitelyTyped project, they could always take it over if they wanted

**Comment by benjaminloerincz** [comment] 2018-10-28 11:38
@ChuckJonas & @d0th3do: Have you seen this? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/6597

**Closed** 2019-02-27 05:18 UTC
